[project]
name = "langchain-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ming", email = "mingsm7518@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain[openai]>=1.4.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
langchain-learning = "langchain_learning:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
